from collections import Counter

with open("data/07.txt") as f:
    data = f.read().split("\n")

# data: list[str] = """.......S.......
# ...............
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............""".split("\n")

beams = {data[0].index("S"): 1}
nextBeam = Counter()

count = 0
for line in data[2::2]:
    for beam in beams:
        if line[beam] == "^":
            count += 1
            nextBeam[beam - 1] += beams[beam]
            nextBeam[beam + 1] += beams[beam]
        else:
            nextBeam[beam] += beams[beam]

    beams = nextBeam
    nextBeam = Counter()

print(count)
print(sum(beams.values()))